name: dl
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # or adjust to your CUDA version
  - pip:
      - transformers
      - datasets
      - huggingface_hub
      - jupyter
